# Generated by Django 3.0 on 2023-04-29 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Glasses_types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('brands', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Brands')),
            ],
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True)),
                ('detail', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genders_in_glasses', models.CharField(blank=True, choices=[('', '-select-'), ('male', 'Male'), ('female', 'Female')], max_length=20, null=True)),
                ('name', models.CharField(max_length=20)),
                ('purchase_price', models.IntegerField(blank=True, null=True)),
                ('sale_price', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='documents')),
                ('size', models.CharField(max_length=15)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('glasses_types', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Glasses_types')),
                ('rack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Rack')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advance', models.IntegerField(blank=True, null=True)),
                ('delivery_date', models.DateField(auto_now_add=True)),
                ('balance', models.IntegerField(blank=True, null=True)),
                ('products', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Products')),
            ],
        ),
        migrations.CreateModel(
            name='Eyesight_nearVision_chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_spherical', models.CharField(blank=True, choices=[('+ 0.25', '+ 0.25'), ('+ 0.50', '+ 0.50'), ('+ 0.75', '+ 0.75'), ('+ 1.00', '+ 1.00')], max_length=20, null=True)),
                ('r_cylindrical', models.CharField(blank=True, choices=[('+ 0.25', '+ 0.25'), ('+ 0.50', '+ 0.50'), ('+ 0.75', '+ 0.75'), ('+ 1.00', '+ 1.00')], max_length=20, null=True)),
                ('r_axis', models.CharField(max_length=20)),
                ('r_va', models.CharField(blank=True, choices=[('+ 0.25', '+ 0.25'), ('+ 0.50', '+ 0.50'), ('+ 0.75', '+ 0.75'), ('+ 1.00', '+ 1.00')], max_length=20, null=True)),
                ('r_option', models.CharField(blank=True, choices=[('', '-Select-'), ('Plano', 'Plano'), ('Foggy', 'Foggy')], max_length=20, null=True)),
                ('l_spherical', models.CharField(blank=True, choices=[('+ 0.25', '+ 0.25'), ('+ 0.50', '+ 0.50'), ('+ 0.75', '+ 0.75'), ('+ 1.00', '+ 1.00')], max_length=20, null=True)),
                ('l_cylindrical', models.CharField(blank=True, choices=[('+ 0.25', '+ 0.25'), ('+ 0.50', '+ 0.50'), ('+ 0.75', '+ 0.75'), ('+ 1.00', '+ 1.00')], max_length=20, null=True)),
                ('l_axis', models.CharField(max_length=20)),
                ('l_va', models.CharField(blank=True, choices=[('+ 0.25', '+ 0.25'), ('+ 0.50', '+ 0.50'), ('+ 0.75', '+ 0.75'), ('+ 1.00', '+ 1.00')], max_length=20, null=True)),
                ('l_option', models.CharField(blank=True, choices=[('', '-Select-'), ('Plano', 'Plano'), ('Foggy', 'Foggy')], max_length=20, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Eyesight_farVision_chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_spherical', models.CharField(blank=True, choices=[('+ 0.25', '+ 0.25'), ('+ 0.50', '+ 0.50'), ('+ 0.75', '+ 0.75'), ('+ 1.00', '+ 1.00')], max_length=20, null=True)),
                ('r_cylindrical', models.CharField(blank=True, choices=[('+ 0.25', '+ 0.25'), ('+ 0.50', '+ 0.50'), ('+ 0.75', '+ 0.75'), ('+ 1.00', '+ 1.00')], max_length=20, null=True)),
                ('r_axis', models.CharField(max_length=20)),
                ('r_va', models.CharField(blank=True, choices=[('+ 0.25', '+ 0.25'), ('+ 0.50', '+ 0.50'), ('+ 0.75', '+ 0.75'), ('+ 1.00', '+ 1.00')], max_length=20, null=True)),
                ('r_option', models.CharField(blank=True, choices=[('', '-Select-'), ('Plano', 'Plano'), ('Foggy', 'Foggy')], max_length=20, null=True)),
                ('l_spherical', models.CharField(blank=True, choices=[('+ 0.25', '+ 0.25'), ('+ 0.50', '+ 0.50'), ('+ 0.75', '+ 0.75'), ('+ 1.00', '+ 1.00')], max_length=20, null=True)),
                ('l_cylindrical', models.CharField(blank=True, choices=[('+ 0.25', '+ 0.25'), ('+ 0.50', '+ 0.50'), ('+ 0.75', '+ 0.75'), ('+ 1.00', '+ 1.00')], max_length=20, null=True)),
                ('l_axis', models.CharField(max_length=20)),
                ('l_va', models.CharField(blank=True, choices=[('+ 0.25', '+ 0.25'), ('+ 0.50', '+ 0.50'), ('+ 0.75', '+ 0.75'), ('+ 1.00', '+ 1.00')], max_length=20, null=True)),
                ('l_option', models.CharField(blank=True, choices=[('', '-Select-'), ('Plano', 'Plano'), ('Foggy', 'Foggy')], max_length=20, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Customer')),
            ],
        ),
    ]
