# Generated by Django 3.0 on 2023-04-29 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='size',
            field=models.CharField(blank=True, choices=[('', '-select-'), ('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], max_length=15, null=True),
        ),
    ]
