# Generated by Django 3.0 on 2023-05-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20230429_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eyesight_farvision_chart',
            name='l_cylindrical',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='eyesight_farvision_chart',
            name='l_spherical',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='eyesight_farvision_chart',
            name='l_va',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='eyesight_farvision_chart',
            name='r_cylindrical',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='eyesight_farvision_chart',
            name='r_spherical',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='eyesight_farvision_chart',
            name='r_va',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='eyesight_nearvision_chart',
            name='l_cylindrical',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='eyesight_nearvision_chart',
            name='l_spherical',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='eyesight_nearvision_chart',
            name='l_va',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='eyesight_nearvision_chart',
            name='r_cylindrical',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='eyesight_nearvision_chart',
            name='r_spherical',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='eyesight_nearvision_chart',
            name='r_va',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
