# Generated by Django 3.0 on 2023-05-04 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_purchase_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase_order',
            name='Date',
        ),
        migrations.AddField(
            model_name='purchase_order',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
