# Generated by Django 3.0 on 2023-05-08 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20230508_0516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase_order',
            old_name='Remarks',
            new_name='remarks',
        ),
    ]
