# Generated by Django 3.0 on 2023-05-08 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20230508_0801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase_order',
            name='vendor',
        ),
        migrations.AlterField(
            model_name='purchase_order_detail_item',
            name='purchase_Order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Purchase_Order'),
        ),
    ]
